development:
 EXCEPTION_MAIL: ""
 ADMIN_MAIL: ""
 DOMAIN: ""
 ADDRESS: ""
 PORT: ""
 EMAIL_DOMAIN: ""
 USER_NAME: ""
 PASSWORD: ""
 EMAIL_FROM: ""
 SECRET_KEY_BASE: ""

production:
 EXCEPTION_MAIL: ""
 ADMIN_MAIL: ""
 DOMAIN: ""
 ADDRESS: ""
 PORT: ""
 EMAIL_DOMAIN: ""
 USER_NAME: ""
 PASSWORD: ""
 EMAIL_FROM: ""
 SECRET_KEY_BASE: ""
 RAILS_SERVE_STATIC_FILES: "true"
